name: Test GetPet mobile application
on: [push, pull_request]
jobs:
  build:
    name: Build GetPet mobile application
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-java@v1
        with:
          java-version: '14.x'

      - run: echo $SIGNING_KEY_BASE64 | base64 -d > android/app/key.jks
        env:
          SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY_BASE64 }}

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: dart --version
      - run: flutter --version

      - run: flutter pub get

      - run: flutter build appbundle
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PATH: key.jks

      - run: flutter build apk
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PATH: key.jks

      - uses: actions/upload-artifact@v2
        name: Upload Android APK
        with:
          name: app-release.apk
          path: build/app/outputs/apk/release/app-release.apk

      - uses: actions/upload-artifact@v2
        name: Upload Android app bundle
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab

  publish_android:
    name: Publish Android app bundle to Play Store
    runs-on: macos-latest
    needs: build
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: app-release.aab

      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: lt.getpet.getpet
          releaseFile: app-release.aab
          track: beta
