name: Build and Publish GetPet mobile application
on: [push, pull_request]
jobs:
  build_android:
    name: Build GetPet Android version
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-java@v1
        with:
          java-version: '14.x'

      - run: echo $SIGNING_KEY_BASE64 | base64 -d > android/app/key.jks
        env:
          SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY_BASE64 }}

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: dart --version
      - run: flutter --version

      - run: flutter pub get

      - run: flutter analyze

      - run: flutter build apk -v
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PATH: key.jks

      - uses: actions/upload-artifact@v2
        name: Upload Android APK
        with:
          name: app-release.apk
          path: build/app/outputs/apk/release/app-release.apk

      - uses: actions/upload-artifact@v2
        name: Upload Proguard mapping.txt
        with:
          name: mapping.txt
          path: build/app/outputs/mapping/release/mapping.txt

      - uses: actions/upload-artifact@v2
        name: Upload pubspec.lock
        with:
          name: pubspec.lock
          path: pubspec.lock

  build_ios:
    name: Build GetPet iOS version
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@master

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: flutter build ios --release --no-codesign -v

  publish_ios:
    name: Publish to AppStore
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@master

      - uses: fregante/setup-git-token@v1
        name: Setup Git Token for Match
        with:
          token: ${{ secrets.GIT_APPLICATION_SPECIFIC_TOKEN }}

      - run: git clone https://github.com/GotPet/certificates.git

      - name: Install provision certificates
        run: (cd ios && fastlane ios certificates)
        env:
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: flutter build ios --release --no-codesign -v

      - name: Publish to AppStore using Fastlane
        run: (cd ios && fastlane ios release)
        env:
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
