name: Release iOS version of GetPet to AppStore
on: [push, pull_request]

#on:
#  push:
#    tags:
#      - v*

jobs:
  release_ios:
    name: Release iOS to AppStore
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@master

      - uses: fregante/setup-git-token@v1
        name: Setup Git Token for Match
        with:
          token: ${{ secrets.GIT_APPLICATION_SPECIFIC_TOKEN }}

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: flutter build ios --release --no-codesign -v

      - name: Publish to AppStore using Fastlane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'ios release'
          subdirectory: 'ios'
        env:
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
